global:
  scrape_interval: 15s  # Tiempo de intervalo para extraer métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Asegúrate de que este sea correcto

  - job_name: 'jenkins'
    static_configs:
      - targets: ['192.168.122.41:8080']  # Cambia <IP_JENKINS> por la IP de 
    metrics_path: '/prometheus'
